name: Set up Python project with Poetry

inputs:
  python_version:
    description: "Python version to install"
    required: true
  poetry_version:
    description: "Poetry version to install"
    required: true

runs:
  using: composite
  steps:
    - name: ✨ Install Poetry
      shell: bash
      run: |
        python3 -m pip install \
            "poetry==${{ inputs.poetry_version }}.*" \
            "poetry-dynamic-versioning<=0.17.1"

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        cache: poetry

    - name: 🛠️ Install project dependencies
      shell: bash
      run: |
        poetry install
        [ "$(poetry version -s)" != "0.0.0" ] \
            || { echo "Versioning broken"; exit 1; }
