---
name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-test-publish:
    name: Python ${{ matrix.python-version }}, Poetry ${{ matrix.poetry-version }}
    runs-on: ubuntu-latest
    env:
      ENABLE_PYPI_PUBLISH: true
      ENABLE_TEST_PYPI_PUBLISH: true
      ENABLE_COVERAGE: true

    strategy:
      matrix:
        python-version:
          - "3.10"
        poetry-version:
          - "1.1.14"

    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v3

      - name: ✨ Install Poetry
        run: pip install poetry==${{ matrix.poetry-version }}

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: 🛠️ Install dependencies
        run: |
          pip install poetry-dynamic-versioning
          poetry install

      - name: 🔥 Test
        run: poetry run poe test

      - name: 📊 Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: env.ENABLE_COVERAGE
        with:
          fail_ci_if_error: true

      - name: 📦 Build package
        if: env.ENABLE_PYPI_PUBLISH
        run: poetry build

      - name: 🔼 Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: |
          env.ENABLE_TEST_PYPI_PUBLISH &&
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags')
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

      - name: ☢️ Publish to PyPI
        if: |
          env.ENABLE_PYPI_PUBLISH &&
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true
